version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: /csharp
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /examples/adapters/go-retryablehttp
    schedule:
      interval: weekly
